name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: pythonblogs
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: $
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy settings
      run: |
        cp settings_local.py.template settings_local.py
    - name: Run Migrations
      run: |
        python manage.py migrate
        python manage.py loaddata data.json
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: pythonblogs
        DBUSER: root
        DBPASSWORD: 
        DBHOST: 127.0.0.1
        DBPORT: $
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: pythonblogs
        DBUSER: root
        DBPASSWORD: 
        DBHOST: 127.0.0.1
        DBPORT: $